name: 'fluent-bit-linter'
description: 'Linter action for Fluent-bit configuration'
branding:
  icon: check
  color: purple
inputs:
  CALYPTIA_API_KEY:
    description: 'Calyptia API Key, it can be found on cloud.calyptia.com under Account > settings'
    required: true
  CONFIG_LOCATION_GLOB:
    description: 'Glob pattern for Fluent-bit location'
    required: true
  GITHUB_TOKEN:
    description: 'Github token, typically available under ${secrets.GITHUB_TOKEN}'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
