name: Fluent linter
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - id: running_linter
        uses: calyptia/fluent-linter-action@gg/adding-parsing-errors-as-annotations
        with:
          CALYPTIA_API_KEY: ${{ secrets.CALYPTIA_API_KEY }}
          CONFIG_LOCATION_GLOB: '__fixtures__/bad-set.conf'
